// ERRORS
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
// MOVVIES TICKET...
export const GET_MOVIE_TICKET = 'GET_MOVIE_TICKET';
export const GET_MOVIES_TICKET = 'GET_MOVIES_TICKET';
export const MOVIES_TICKET_LOADING = 'MOVIES_T_LOADING';
export const GET_DRIVERS = 'GET_DRIVERS';
export const GET_DRIVER = 'GET_DRIVER';
export const TOGGLE_DRIVER_LOADING = 'TOGGLE_DRIVER_LOADING';
