// ERRORS
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// MOVIES...
export const GET_MOVIES = 'GET_MOVIES';
export const GET_MOVIES_LOADING = 'GET_MOVIES_LOADING';
// MOVVIES TICKET...
export const GET_MOVIE_TICKET = 'GET_MOVIE_TICKET';
export const GET_MOVIES_TICKET = 'GET_MOVIES_TICKET';
export const MOVIES_TICKET_LOADING = 'MOVIES_T_LOADING';

// SHOWTIMES...
export const GET_SHOWTIMES = 'GET_SHOWTIMES';
export const GET_SHOWTIME = 'GET_SHOWTIME';
export const SHOWTIME_LOADING = 'SHOWTIME_LOADING';

// GIFTING...
export const GIFT_LOADING = 'GIFT_LOADING';
export const GET_GIFTS = 'GET_GIFTS';
export const GET_GIFT = 'GET_GIFT';
// VOUCHERS...

// MERCHANTS...
export const MERCHANT_LOADING = 'MERCHANT_LOADING';
export const GET_MERCHANT = 'GET_MERCHANT';
export const GET_MERCHANTS = 'GET_MERCHANTS';

// TRANSACTIONS...
export const TRANSACTION_LOADING = 'TRANSACTION_LOADING';
export const GET_DAILY_TRANSACTION = 'GET_DAILY_TRANSACTION';
export const GET_WEEKLY_TRANSACTION = 'GET_WEEKLY_TRANSACTION';
export const GET_MONTHLY_TRANSACTION = 'GET_MONTHLY_TRANSACTION';
export const GET_RANGE = 'GET_RANGE';

// CINEMAS
export const CINEMA_LOADING = 'CINEMA_LOADING';
export const GET_CINEMAS = 'GET_CINEMAS';

// REPORTS...

// REDEMPTIONS...

// DYNAMIC IMAGES...

//
